title: Pure-fun
description: Purely functional data structures for OCaml, translated from Chris Okasaki's book "Purely Functional Data Structures"
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
